MESSAGE_BROKER_BASE_PATH = "iot/lwx123321/test/"

# Watering Decision-Making
MIN_RAIN_PROBABILITY = 1.0
MIN_CLOUDINESS_FOR_WATERING = 80
DEFAULT_ADJUSTMENT_FACTOR = 1.1
TEMP_ADJUSTMENT_FACTOR = 0.02
BASELINE_TEMP_FOR_ADJUSTMENT = 20
HUMIDITY_ADJUSTMENT_FACTOR = 0.01
BASELINE_HUMIDITY_FOR_ADJUSTMENT = 60

# Watering Duration (based on garden characteristics)
DEPTH = 0.3
DENSITY = 1300
CUBIC_AREA = 50
VALVE_FLOW_RATE = 30*60
