
MESSAGE_BROKER_BASE_PATH = "iot/lwx123321/test/"



DEFAULT_SOIL_TYPE = "Clay"
MIN_RAIN_PROBABILITY = 1.0
MIN_CLOUDINESS_FOR_WATERING = 20
from datetime import timedelta
WATERING_TIME_WINDOW = timedelta(hours=1)
DEFAULT_ADJUSTMENT_FACTOR = 1.1
SOIL_ABSORPTION_FACTOR = 0.7
TEMP_ADJUSTMENT_FACTOR = 0.02
BASELINE_TEMP_FOR_ADJUSTMENT = 20
HUMIDITY_ADJUSTMENT_FACTOR = 0.01
BASE_WATERING_DURATION = 15
TEMP_THRESHOLD = 25
HUMIDITY_THRESHOLD = 40
BASELINE_HUMIDITY_FOR_ADJUSTMENT = 60
