
MESSAGE_BROKER_BASE_PATH = "iot/lwx123321/test/"


# Watering Decision Making
DEFAULT_SOIL_TYPE = "Clay"
WATERING_TOPIC_BASE_PATH = 'device/command/irrigator/'
CSV_FILE_PATH = 'weather_turin.csv'
MIN_RAIN_PROBABILITY = 1.0
MIN_CLOUDINESS_FOR_WATERING = 0
from datetime import timedelta
WATERING_TIME_WINDOW = timedelta(hours=1)
DEFAULT_ADJUSTMENT_FACTOR = 1.1
SOIL_ABSORPTION_FACTOR = 0.7
TEMP_ADJUSTMENT_FACTOR = 0.02
BASELINE_TEMP_FOR_ADJUSTMENT = 20
HUMIDITY_ADJUSTMENT_FACTOR = 0.01
BASE_WATERING_DURATION = 15
TEMP_THRESHOLD = 25
HUMIDITY_THRESHOLD = 40
BASELINE_HUMIDITY_FOR_ADJUSTMENT = 60


#Watering_coordinator
CHECK_INTERVAL = 300
RUNNING_CHECK_INTERVAL = 2

#Watering Duration
SCALING_FACTOR = 20