from constants import entity

INFLUX_BASE_ROUTE = '/device/'
TEMPERATURE_GET = INFLUX_BASE_ROUTE + entity.TEMPERATURE
HUMIDITY_GET = INFLUX_BASE_ROUTE + entity.HUMIDITY
LIGHT_GET = INFLUX_BASE_ROUTE + entity.LIGHT
GATE_GET = INFLUX_BASE_ROUTE + entity.GATE
IRRIGATOR_GET = INFLUX_BASE_ROUTE + entity.IRRIGATOR
