import entity

INFLUX_BASE_PATH = "iot/lwx123321/test/"
TEMPERATURE_TOPIC = INFLUX_BASE_PATH + entity.TEMPERATURE
HUMIDITY_TOPIC = INFLUX_BASE_PATH + entity.HUMIDITY
LIGHT_TOPIC = INFLUX_BASE_PATH + entity.LIGHT
GATE_TOPIC = INFLUX_BASE_PATH + entity.GATE
IRRIGATOR_TOPIC = INFLUX_BASE_PATH + entity.IRRIGATOR
