version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile-user
    ports:
      - "8083:8083"
    depends_on:
      - influx_service
      - mysql_service
    environment:
      - INFLUXDB_HOST=influx_service
      - INFLUXDB_PORT=8084
      - MYSQL_HOST=mysql_service
      - MYSQL_PORT=8085
    networks:
      - app-network

  influx_service:
    build:
      context: .
      dockerfile: Dockerfile-influx
    ports:
      - "8084:8084"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - app-network

  mysql_service:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "8085:8085"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./message_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  influxdb_data:
  mysql_data:

networks:
  app-network:
    driver: bridge
