FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . /app

EXPOSE 5000

ENV PYTHONPATH="/app"

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "third_party/open_weather_map/__main__.py"]
