version: '3.8'

services:
  user_service:
    build: ./service/user
    ports:
      - "8083:8083"
    depends_on:
      - influx_service
      - mysql_service
    environment:
      - INFLUXDB_HOST=influx_service
      - INFLUXDB_PORT=8084
      - MYSQL_HOST=mysql_service
      - MYSQL_PORT=8085

  influx_service:
    build: ./database/influxdb
    ports:
      - "8084:8084"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_URL}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PWD}

  mysql_service:
    build: ./mysql_service
    ports:
      - "8085:8085"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  influxdb_data:
  mysql_data:
