version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile-user
    ports:
      - "8083:8083"
    depends_on:
      - influx_service
      - mysql_service
    environment:
      - INFLUXDB_HOST=influx_service
      - INFLUXDB_PORT=8084
      - MYSQL_HOST=mysql_service
      - MYSQL_PORT=8085
    networks:
      - app-network

  influx_service:
    build:
      context: .
      dockerfile: Dockerfile-influx
    ports:
      - "8084:8084"
    depends_on:
      - mysql_service
    environment:
      - MYSQL_HOST=mysql_service
      - MYSQL_PORT=8085
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - app-network

  mysql_service:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "8085:8085"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  influxdb_data:
  mysql_data:

networks:
  app-network:
    driver: bridge
